#  Apple 取货监控 —— Windows 后台常驻安装脚本
#
#  双击「一键部署.bat」会自动调用本脚本。
#  也可手动运行：
#     powershell -ExecutionPolicy Bypass -File scripts\install-windows-task.ps1
#     powershell -ExecutionPolicy Bypass -File scripts\install-windows-task.ps1 -DryRun
#     powershell -ExecutionPolicy Bypass -File scripts\install-windows-task.ps1 -Uninstall
#
#  「不打扰前方工作」的实现方式：
#   任务动作是 wscript.exe 跑一个 VBS，VBS 以「隐藏窗口」方式启动 node 并等待它。
#   所以既没有黑窗口弹出来，任务又能在 node 崩溃时按计划自动重启。

[CmdletBinding()]
param(
  [switch]$DryRun,      # 只检查环境并打印将要做什么，不注册任务
  [switch]$Uninstall,   # 卸载任务
  [switch]$NoStart      # 注册后不立即启动
)

$ErrorActionPreference = 'Stop'
$TaskName = 'ApplePickupMonitor'
$ProjectDir = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Say($msg, $color = 'Gray') { Write-Host $msg -ForegroundColor $color }

Say ""
Say "=== Apple 取货监控 · 后台常驻安装 ===" 'Cyan'
Say "项目目录: $ProjectDir" 'DarkGray'
Say ""

# ---------- 卸载 ----------
if ($Uninstall) {
  $t = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($t) {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Say "已卸载任务计划: $TaskName" 'Green'
  } else {
    Say "任务 $TaskName 不存在，无需卸载。" 'Yellow'
  }
  Say "   （日志和配置仍保留在项目目录，可手动删除）" 'DarkGray'
  exit 0
}

if ($DryRun) { Say "【DRY-RUN】只做检查，不会注册任何任务`n" 'Yellow' }

# ---------- 1. 找 node ----------
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
  Say "✗ 未检测到 Node.js" 'Red'
  Say "  请先安装 Node.js LTS（一路下一步即可）: https://nodejs.org" 'Yellow'
  exit 1
}
$nodePath = $nodeCmd.Source
$nodeVer = (& node -v)
Say "✓ Node.js $nodeVer  ($nodePath)" 'Green'

# ---------- 2. 依赖 ----------
$nm = Join-Path $ProjectDir 'node_modules'
if (Test-Path $nm) {
  Say "✓ 依赖已存在，跳过 npm install" 'Green'
} else {
  if ($DryRun) {
    Say "· 将执行 npm install" 'Gray'
  } else {
    Say "· 正在安装依赖…" 'Gray'
    Push-Location $ProjectDir
    try { & npm install --no-audit --no-fund | Out-Null } finally { Pop-Location }
    if (-not (Test-Path $nm)) { Say "✗ 依赖安装失败" 'Red'; exit 1 }
    Say "✓ 依赖安装完成" 'Green'
  }
}

# ---------- 3. 邮箱配置 ----------
$envFile = Join-Path $ProjectDir '.env'
if (Test-Path $envFile) {
  Say "✓ 邮箱已配置（.env 已存在），跳过向导" 'Green'
} else {
  if ($DryRun) {
    Say "· 将运行配置向导（需要输入收件邮箱、发件邮箱、授权码）" 'Gray'
  } else {
    Say ""
    Say "· 首次部署，进入邮箱配置向导…" 'Cyan'
    Push-Location $ProjectDir
    try { & node 'src/setup.js' } finally { Pop-Location }
    if (-not (Test-Path $envFile)) { Say "✗ 配置未完成，已中止" 'Red'; exit 1 }
  }
}

# ---------- 4. 生成隐藏启动器 ----------
$vbs = Join-Path $ProjectDir 'scripts\run-hidden.vbs'
$vbsContent = @"
' Auto-generated by install-windows-task.ps1 - do not edit by hand.
' Starts the monitor with a hidden window (no disturbance to the desktop)
' and waits for it, so Task Scheduler can restart it if it crashes.
' NOTE: keep this file ASCII-only - Windows Script Host reads .vbs as ANSI.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$ProjectDir"
sh.Run """$nodePath"" ""$ProjectDir\src\index.js""", 0, True
"@
if ($DryRun) {
  Say "· 将生成隐藏启动器: $vbs" 'Gray'
} else {
  Set-Content -Path $vbs -Value $vbsContent -Encoding ASCII
  Say "✓ 已生成隐藏启动器（无窗口运行）" 'Green'
}

# ---------- 5. 注册任务计划 ----------
$isAdmin = ([Security.Principal.WindowsPrincipal] `
  [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

$action = New-ScheduledTaskAction -Execute 'wscript.exe' `
  -Argument "`"$vbs`"" -WorkingDirectory $ProjectDir

$settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -StartWhenAvailable `
  -RestartCount 999 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
  -MultipleInstances IgnoreNew

if ($isAdmin) {
  $triggers = @((New-ScheduledTaskTrigger -AtStartup), (New-ScheduledTaskTrigger -AtLogOn))
  $runLevel = 'Highest'
  Say "· 检测到管理员权限：配置为「开机自启 + 登录自启」" 'DarkGray'
} else {
  $triggers = @((New-ScheduledTaskTrigger -AtLogOn))
  $runLevel = 'Limited'
  Say "· 未以管理员运行：配置为「登录后自启」（同样后台无窗口）" 'DarkGray'
  Say "  想要真正的开机自启（无需登录），请右键以管理员身份运行本脚本。" 'DarkGray'
}

if ($DryRun) {
  Say ""
  Say "【DRY-RUN】将注册任务：$TaskName" 'Yellow'
  Say "  动作    : wscript.exe `"$vbs`"" 'Gray'
  Say "  触发器  : $($triggers.Count) 个（$(if ($isAdmin) { '开机 + 登录' } else { '登录' })）" 'Gray'
  Say "  运行级别: $runLevel" 'Gray'
  Say "  策略    : 崩溃后每 1 分钟自动重启，无运行时长限制" 'Gray'
  Say ""
  Say "DRY-RUN 通过：环境检查全部正常，真正执行时会注册并启动。" 'Green'
  exit 0
}

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
  Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
  Say "· 已移除同名旧任务" 'DarkGray'
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $triggers `
  -Settings $settings -RunLevel $runLevel `
  -Description '监控 Apple Store 广东道门市取货库存，有货时邮件通知（后台无窗口运行）' | Out-Null

Say "✓ 已注册任务计划: $TaskName" 'Green'

if (-not $NoStart) {
  Start-ScheduledTask -TaskName $TaskName
  Start-Sleep -Seconds 4
  $info = Get-ScheduledTask -TaskName $TaskName | Get-ScheduledTaskInfo
  if ($info.LastTaskResult -eq 267009 -or $info.LastTaskResult -eq 0) {
    Say "✓ 已启动，正在后台静默运行" 'Green'
  } else {
    Say "· 已启动（状态码 $($info.LastTaskResult)）" 'Gray'
  }
}

Say ""
Say "──────────────────────────────────────────────" 'DarkGray'
Say " 常用操作：" 'White'
Say "   查看日志 : monitor.log   （或双击 查看日志.bat）" 'Gray'
Say "   停止监控 : 双击 停止监控.bat" 'Gray'
Say "   查看状态 : schtasks /Query /TN $TaskName /V /FO LIST" 'Gray'
Say "   卸载     : powershell -ExecutionPolicy Bypass -File scripts\install-windows-task.ps1 -Uninstall" 'Gray'
Say "──────────────────────────────────────────────" 'DarkGray'
Say ""
